# Site settings
title: Photofil
email: philip.omlin@gmail.com
author: Philip Omlin
description: blabla
url: fotophil.ch

# Build settings
permalink: :title/
sass:
  sass_dir: assets/css

# Social icons
show_social_icons: true
github_username: someGithubUser
twitter_username: someTwitterUser

# Github
url: pomlin83
baseurl: fotophil
