# Site settings
title: fotophil.ch
email: philip.omlin@gmail.com
author: Philip Omlin
description: blabla

# Build settings
#permalink: :title/
sass:
  sass_dir: assets/css

# Social icons
show_social_icons: true
github_username: someGithubUser
twitter_username: someTwitterUser

# Github
url: pomlin83
